### ISSUE TITLE
UX tidyup

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-modelli-ng-tool#3]
- [x] Comment out nav
- [x] Rename entire page: "Clinical data models for humans"
- [x] Rename schema to tooth exam
- [x] Kill schema link and description title 
- [x] Move table into panel like this https://getbootstrap.com/docs/3.3/components/#panels-tables
- [x] GH Issue to provide feedback on this row, make the link provide an issue template 
- [x] Move edit data model to schema description row
- [x] Show example widget in data type
- [x] In data type where it says string, display text where it says boolean display yes/no

**Comment by pacharanero** [comment]
>  GH Issue to provide feedback **on this row**, make the link provide an issue template


I'm going to move this one out into its [own Issue](https://github.com/openhealthcare/opal-modelli-ng-tool/issues/5) because it's slightly more complicated than a UX tweak. I can do a simple Issue Template in the interim.

**Comment by pacharanero** [comment]
99% done except I am having a problem conditionally displaying input boxes and checkboxes without them being weirdly sized. Have a look @davidmiller and see if there's a bootstrap detail I'm missing.

**Comment by pacharanero** [comment]
closed via #8 and #11
